name: Telegram Auto Sender

on:
  schedule:
    - cron: "*/30 * * * *"  # Har 30 minutda tekshiradi
  workflow_dispatch:

concurrency:
  group: telegram-sender
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python oâ€˜rnatish
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kutubxonalar
        run: pip install -r requirements.txt

      - name: Ishga tushirish
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION: ${{ secrets.SESSION }}
          ALERT_CHAT: ${{ secrets.ALERT_CHAT }}
        run: python auto.py
        
